### ISSUE TITLE
var is referenced but not assigned for env variables

### ISSUE THREAD

**Issue by johnbieren** [chmeliik/checkton#45]
The shellchecker reports `var is referenced but not assigned.` when you define something in the tekton step env. For example, this
```
      env:
        - name: gwCert
           valueFrom:
            secretKeyRef:
              name: $(params.gwSecret)
              key: cert
```
results in shellchecker reporting
```
SC2154
gwCert is referenced but not assigned.
```
